name: Bingo
version: '${project.version}'
main: fr.sny1411.bingo.Bingo
api-version: '1.20'
commands:
  newGame:
    description: create a new game
    permission: bingo.newGame
  start:
    description: start game
    permission: bingo.start
  bingo:
    description: open bingo gui
  testPack:
    description: test pack du serveur
    permission: bingo.testPack
  valid:
    description: force la validation d'un défi
    permission: bingo.valid
  stopGame:
    description: end of game
    permission: bingo.stopGame
  result:
    description: show result
    permission: bingo.result
  bonus:
    description: valid bonus command
  spec:
    description: permet de se mettre en spectateur
