[versions]
paper-api = "1.20.1-R0.1-SNAPSHOT"
paperlib = "1.0.8"
shadow = "9.6.1"
run-paper = "3.1.0"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
paperlib = { module = "io.papermc:paperlib", version.ref = "paperlib" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
